### ISSUE TITLE
發生錯誤

### ISSUE THREAD

**Issue by NickYuu** [appleboy/docker-multi-stage-build#1]
我運行 docker build -t appleboy/go-app .
發生下面錯誤
Sending build context to Docker daemon  38.4 kB
Step 1/7 : FROM golang:alpine AS build-env
Error parsing reference: "golang:alpine AS build-env" is not a valid repository/tag: invalid reference format

**Comment by appleboy** [comment]
@NickYuu What is your docker version? only `v17.05.0-ce` support multi-stage build.

```
docker version
```
